# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f08639a8287e527e8c70f8aa91aca7160123552e0c215b18ddf8a8be8bd44af1b4971ee23715fca10063f961d2629d7bac24d987344e9ef7f86e5ee73fc3be30

test:
  secret_key_base: c88ddaf26c9a4e86b590036a1dfdb242b02692d9c3d2333b1937e70f61a493ad1ac3d7200dabc668f163a9caf7c0bb8419901b01eb19fbae4f6d25310ad38c37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
